#!/usr/bin/env bash
set -ue

binfile=$(mktemp)
objfile=$(mktemp)
configfile=$(mktemp)

echo '
MEMORY {
    CODE:     file = %O, start = $8000, size = $8000-6, fill = yes;
}
SEGMENTS {
    CODE:        load = CODE, type = rw;
}
' > $configfile


ca65 $1 -o $objfile
ld65 $objfile -o $binfile --config $configfile
t65sim $binfile
